name: "SmartPlaylist2PlaylistHarder"
guid: "5A63FE63-765F-43F7-A129-661E839F83D5"
imageUrl: ""
version: "1.4.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "JMiles42"
overview: "Smart Playlist 2 Playlist Harder! Is a system to automatically generate playlists based on a set of rules\nBuilt off of the base of SmartPlaylist by ankenyr"
description: >
  Smart Playlist 2 Playlist Harder!.
  Is a system to automatically generate playlists based on a set of rules.
  Built off of the base of SmartPlaylist by ankenyr.
category: "Playlist"
artifacts:
  - "Jellyfin.Plugin.SmartPlaylist.dll"
changelog: >
  Updated Ordering